apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: green-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/wlgns1210/wskd1-green.git'
    targetRevision: main
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: green
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
