apiVersion: v1
kind: Service
metadata:
  name: green-service
  namespace: wsk25
spec:
  type: NodePort
  selector:
    app: green    
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 8080  
